disabled_rules:
  - large_tuple
  - class_delegate_protocol
  - closure_parameter_position
  - colon
  - control_statement
  - cyclomatic_complexity
  - empty_parentheses_with_trailing_closure
  - file_length
  - force_cast
  - function_body_length
  - function_parameter_count
  - identifier_name
  - line_length
  - nesting
  - no_fallthrough_only
  - opening_brace
  - orphaned_doc_comment
  - shorthand_operator
  - statement_position
  - switch_case_alignment
  - todo
  - type_body_length
  - type_name
  - unused_setter_value
  - vertical_whitespace
  - comma
  - mark
  - is_disjoint
  - notification_center_detachment
  - unused_capture_list
  - multiple_closures_with_trailing_closure
included:
  - Spendora
excluded:
  - Carthage
  - Pods
  - External
  - Submodules
  - Generated
  - fastlane
  - AnimationAssets
  - Assets.xcassets
analyzer_rules:
  - unused_import
