# .circleci/config.yml
version: 2.1

jobs:
    build-and-test:
        macos: "14.2.0"
    environment:
        FL_OUTPUT_DIR: output
    steps:
        - checkout
        - run:
            name: Build and run tests
            command: fastlane ios ghc_scan_test
        - store_test_results:
            path: build/fastlane/scan_output
        - store_artifacts:
            path: ~/Library/Logs/DiagnosticReports
        - store_artifacts:
            path: OneAppTests/Snapshots/FailReports
        - store_artifacts:
            path: /tmp/simulator-build

workflows:
    version: 2
    build-and-test:
        jobs:
            -build-and-test
