version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: "12.4.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 14 (16.2)
            SCAN_SCHEME: Spendora
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output


workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
